export const routePaths = {
  HOME: 'home',
  LOGIN: 'login',
  MY_COLLECTION: 'my-collection',
  MY_COLLECTION_IMAGES: 'images',
  MY_COLLECTION_LINKS: 'links',
  MY_COLLECTION_TEXTS: 'texts',
  PROFILE: 'profile',
  RESET_PASSWORD: 'reset-password',
  SHARED_COLLECTION: 'shared-collection',
  SHARED_COLLECTION_IMAGES: 'images',
  SHARED_COLLECTION_LINKS: 'links',
  SHARED_COLLECTION_TEXTS: 'texts',
  SIGNUP: 'signup',
  TEXTS: 'texts',
  LINKS: 'links',
  UPLOAD: 'upload',
  UPLOAD_IMAGE: 'image',
  UPLOAD_LINK: 'link',
  UPLOAD_TEXT: 'text',
};
