export const routePaths = {
  HOME: 'home',
  LOGIN: 'login',
  RESET_PASSWORD: 'reset-password',
  SIGNUP: 'signUp',
  SEND: 'send',
  SEND_ALL: 'send-all',
  SEND_IMAGE: 'send-image',
  SEND_LINK: 'send-link',
  SEND_TEXT: 'send-text',
  UPLOAD: 'upload',
  UPLOAD_IMAGE: 'upload-image',
  UPLOAD_LINK: 'upload-link',
  UPLOAD_TEXT: 'upload-text',
};
